import { FileText } from 'lucide-react';

/**
 * Displays the AI-generated summary from Gemini.
 */
export default function SummaryCard({ summary }) {
  if (!summary) return null;

  return (
    <div className="glass-card p-6 animate-slide-up">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-indigo-500/20 flex items-center justify-center">
          <FileText size={16} className="text-indigo-400" />
        </div>
        <p className="text-xs font-semibold text-[#6b6f8a] uppercase tracking-widest">
          AI Summary
        </p>
      </div>

      <blockquote className="relative pl-4 border-l-2 border-indigo-500/50">
        <p className="text-[#d4d4f0] leading-relaxed text-sm sm:text-base">
          {summary}
        </p>
      </blockquote>

      <p className="text-[10px] text-[#6b6f8a] mt-4">
        Generated by Google Gemini AI · Summary is based solely on the provided review text
      </p>
    </div>
  );
}
